server {
    listen 0.0.0.0:80;
    root /usr/share/nginx/html/;
    index index.php;

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html/$fastcgi_script_name;
    }
}